version: "3"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/go/src/buildspace
    working_dir: /go/src/buildspace
    command: ["bash"]