# For full config options, check the docs:
#    docs.serverless.com

service: rda

provider:
  name: aws
  runtime: go1.x
  timeout: 240
  versionFunctions: false
  memorySize: 128

  # you can overwrite defaults here
  #  stage: dev
  region: us-east-1

  # you can define service wide environment variables here
  environment:
    stage: ${self:custom.stage}
    region: ${self:custom.region}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
      Resource: "*"

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

package:
  exclude:
    - ./**
  include:
    - ./bin/**
    - ./config.json

functions:
  cron:
    handler: bin/rda
    events:
      - schedule: cron(10 9 * * ? *) # every day at 09:10 GMT
